- miette-derive/src/code.rs
- miette-derive/src/diagnostic.rs
- miette-derive/src/help.rs
- miette-derive/src/lib.rs
- miette-derive/src/severity.rs
- miette-derive/src/snippets.rs
- tests/derive.rs
> Support for deriving snippet method

- .github/workflows/ci.yml
Fixes: https://github.com/zkat/miette/issues/2
> meta: set up CI

- src/printer/graphical_printer.rs
- tests/printer.rs
> Clamp highlight length to at least 1

- src/source_impls.rs
> impl Source for str, &str (make &'static str usable for testing)

- src/printer/graphical_printer.rs
- src/printer/narratable_printer.rs
- tests/narrated.rs
- tests/printer.rs
> Show snippet message for unnamed sources

- src/protocol.rs
It could be useful to have less confusion I had in #75
> feat(SourceSpan): add impl From<Range>

- Cargo.toml
- src/handlers/json.rs
- src/handlers/mod.rs
- tests/test_json.rs
> feat(handlers): Add JSON handler

- src/handlers/json.rs
- tests/test_json.rs
A part of fix of #99, follow up of #117
Forgot this one. Also, I think "debug" handler can stay as is, right?
> fix(handlers): source code propagation for JSON handler

- src/handlers/graphical.rs
Closes #136
I've done my best to match existing code style.
> Allow GraphicalReportHandler to disable url display

- src/handler.rs
This wasn't actually respected 🙃
Closes #134
> Apply MietteHandlerOpts::graphical_theme

- Cargo.toml
To selfishly remove the duplicate I get when using `miette` with the latest `clap@v3` 💜
> chore(deps): Update textwrap to 0.15.0

- src/eyreish/error.rs
- tests/test_convert.rs
This is more of a wild guess and therefore requires someone to review who understands whether this is implemented correctly.
I don't have enough experience with Rust VTables yet.
The unit tests seem sane and succeed, though.
Closes https://github.com/zkat/miette/issues/146.
> Add conversion from Report to Box<dyn Error>

- Makefile.toml
- README.md
- miette-derive/src/diagnostic.rs
- miette-derive/src/help.rs
- miette-derive/src/lib.rs
- src/lib.rs
- tests/derive.rs
Fixes: https://github.com/zkat/miette/issues/148
> feat(help): update macro to allow optional help text

- miette-derive/src/label.rs
- src/handlers/graphical.rs
- src/lib.rs
- tests/derive.rs
Fixes: https://github.com/zkat/miette/issues/110
> feat(labels): allow optional labels in derive macro

- miette-derive/src/help.rs
- miette-derive/src/label.rs
- src/lib.rs
- src/macro_helpers.rs
- tests/derive.rs
cheers to @jam1garner for this awesome hack!
> Option magic for label and help attributes in macro

- src/handlers/graphical.rs
- src/handlers/narratable.rs
Fixes: https://github.com/zkat/miette/issues/139
> feat(related): print related prefixes according to severity

- src/handlers/graphical.rs
- tests/graphical.rs
Fixes: https://github.com/zkat/miette/issues/130
> fix(graphical): fix issue with duplicate labels when span len is 0

- src/handlers/json.rs
- tests/test_json.rs
Fixes: https://github.com/zkat/miette/issues/187
> Support causes in JSON renderer

- src/protocol.rs
> Fix off-by-one error in SourceOffset::from_location

- src/handlers/graphical.rs
- tests/graphical.rs
Fixes: #203
A classic off-by-one error, sorry :)
> fix(graphical): Fix panic when span covers full line

- src/protocol.rs
Implements #239, pending acceptance.
> feat(protocol): implement `Ord` for `Severity`

- src/handlers/graphical.rs
- src/source_impls.rs
While investigating a perf issue (https://github.com/Boshen/oxc/issues/166) when many miette errors were printed, before I understood the cause (miette is not the problem) I made these local changes.
> refactor: nit perf improvements

- CODE_OF_CONDUCT.md
- src/handlers/graphical.rs
- tests/graphical.rs
> Correct some typos

- src/handlers/graphical.rs
- tests/graphical.rs
Closes #85 
Now miette supports this!
And this:
If you disagree about the specifics of how this is rendered, feel free to comment and I'll change it. If you don't like the way I programmed it as well :). Hope you like it!
> Multiline label

- src/protocol.rs
- tests/derive.rs
Breaking change: SourceOffset -> usize in SourceSpan
> feat(source): use `usize` for length

- src/chain.rs
- src/eyreish/error.rs
- src/eyreish/kind.rs
- src/eyreish/mod.rs
Closed #375
copied https://github.com/dtolnay/anyhow/commit/fa9bcc0457a2e51593b874cc2f8bcb5608ad43fe
> refactor: mark error constructors cold

- src/diagnostic_chain.rs
- src/eyreish/ptr.rs
- src/protocol.rs
- src/source_impls.rs
Clippy check is currently failing on `main`, this PR fixes it.
> fix(clippy): elide lifetimes

- Cargo.toml
Small request to bump unicode-width please!
> chore: update unicode-width dependency to v0.2.0
