miette-derive/src/code.rs, miette-derive/src/diagnostic.rs, miette-derive/src/diagnostic_arg.rs, miette-derive/src/help.rs, miette-derive/src/severity.rs, miette-derive/src/snippets.rs, miette-derive/src/url.rs, miette-derive/src/utils.rs, src/compile_test.rs, src/lib.rs, tests/derive.rs
Fixes #16.
I struggled hard naming some of the syntax structs/enums so rename them if you can think of something better. I also didn't implement it for single field structs, mainly because I couldn't be bothered. The only reason I can imagine that being useful is wrapping a foreign diagnostic type, and adding impls for std traits like PartialEq, etc. If anyone needs that it wouldn't be hard.
=> Add `#[diagnostic(transparent)]`

src/printer/graphical_printer.rs, tests/printer.rs
The tests reflected the incorrect behaviour, skipping a line at at the very end.
=> Only inc the line count if we haven't already done so with a char

src/source_impls.rs
The bound `T: Clone` on [the `Source` implementation for `Cow<'_, T>`](https://github.com/zkat/miette/blob/84219f6c80c2c432fbeb4c40a591380285de8767/src/source_impls.rs#L87) is too restrictive. `Cow<'_, T>` [implements `Clone` using `T: ToOwned`](https://github.com/rust-lang/rust/blob/6cfa773583bb5123e630668f5bfe466716225546/library/alloc/src/borrow.rs#L199) and `T` need not implement `Clone` itself. This change relaxes the bounds so that the `Source` implementation includes `Cow<'_, str>`. Please take a look. Thanks!
=> Remove bound `T: Clone` from `Source` implementation for `Cow`.

src/handlers/graphical.rs, tests/printer.rs
when the highlight span starts at the very begining of a line, the highlight currently includes the line above
Before:
After:
=> Fix end of previous line wrongly being included in highlight

README.md
It seems it's a deprecated method
=> docs: fix set_reporter to set_hook

src/source_impls.rs
Fixes: #76 
See #76 for more information.
=> fix(read_span) prevent multilines MietteSpanContents from skipping lines

README.md, src/handler.rs, src/handlers/graphical.rs, tests/graphical.rs, tests/test_location.rs
Closes #73 
Makes it possible to replace tabs with spaces. This is needed because highlight line renderers are not aware of displayed tab width and appear in wrong places if line contains tabs.
=> Add replace tabs with spaces option

src/chain.rs, src/eyreish/mod.rs, src/lib.rs, tests/test_context.rs
This fixes all current compiler and clippy warnings.
It looks like wrong `Chain` type was exported. This is technically could be seemed as a breaking change, but in reality should not break anyone since that type was not used and could not be created I think.
=> fix(chain): correct `Chain` structure exported

src/handlers/json.rs, tests/test_json.rs
Currently JSON handler can produce invalid JSON.
There are string escaping bugfixes:
1. Things like `\n` are not doubly-escaped any more
2. The backslash `\` itself in the source is escaped
And also `related` array was not comma-delimited.
=> Fix bugs in JSON handler

src/eyreish/into_diagnostic.rs, src/eyreish/mod.rs
Note: `DiagnosticError` is a private type, `Report` returned from
`into_diagnostic()` instead.
=> docs: fix mentions of eyre and DiagnosticError

src/handler.rs
This is a start, but I still want to add an environment variable to force "plaintext" mode. Maybe just "MIETTE_PLAINTEXT" or "PLAINTEXT_ERRORS"?
I'll sleep on it. Any opinions are welcome, tho.
Note that this PR is a breaking change, because some users possibly rely on this behavior to even be able to read their output.
=> fix(colors): treat no-color mode as no-color instead of narratable

Cargo.toml, src/handlers/narratable.rs, tests/narrated.rs
Fixes #106
While fixing the bug I've also extended the handler to print not just
where label starts but also where label ends.
Also implements #97, but for narratabble handler only.
This adds dependency on `unicode-width`, but it was already in the
dependency chain (`textwidth` depends on it).
=> fix(handlers): Fix label position

src/eyreish/error.rs, tests/test_handler_access.rs
Techically there was a hidden undocumented `context` method. But it was
just copied from the `eyre` and there is no evidence that it was used by
any user in miette (the method was an alias for `.handler()`).
Fixes #108
=> feat(Report): adds `.context()` method to the `Report`

README.md, src/eyreish/error.rs, src/eyreish/wrapper.rs, src/handlers/graphical.rs, src/handlers/narratable.rs, tests/graphical.rs, tests/narrated.rs
Fixes #64 and #99
@zkat, I'm not sure what you mean by `source_code()` and `with_source_code()` code in #64. Since the report object is already an error it doesn't make much sense to put a lambda there. And since `source_code()` might be confused with `Diagnostic::source_code` I think `with_` works better.
The internal `WithSourceCode` wrapper is designed in a way that would allow adding `with_source_code` on error or even `WrapErr`. But I'm not sure these are needed, so did not include in the PR.
=> More ergonomic source code handling

miette-derive/src/related.rs, src/eyreish/error.rs, tests/derive.rs
Fixes #119
I'm not sure if using `borrow()` should be thought of as a great way to handle the issue or it's a hack.
The alternative would be to make some private trait that we have to expose using `docs(hidden)` for derive to use. But this may also make error reporting confusing (i.e. failing with trait name that can't be found anywhere in the docs).
I think `Borrow` is safe to implement for the `Report`. I had a tiny concern that it make prohibit using error types with (non-static) lifetimes in `related`. But I think it's *not the case*. Although, I could not test that as code-gen for nonstatic lifetimes in `related` is untested and broken for now.
=> feat(derive): allow `Report` in `related`

README.md, README.tpl, miette-derive/src/utils.rs, rustfmt.toml, src/error.rs, src/eyreish/error.rs, src/eyreish/into_diagnostic.rs, src/eyreish/macros.rs, src/eyreish/mod.rs, src/handler.rs, src/handlers/debug.rs, src/handlers/graphical.rs, src/handlers/json.rs, src/handlers/narratable.rs, src/handlers/theme.rs, src/lib.rs, src/named_source.rs, src/protocol.rs, src/source_impls.rs, tests/graphical.rs, tests/narrated.rs
* Fixed all intra-doc links and their formatting.
* Added clarification for `anyhow`/`eyre` users.
* Removed `MietteError::SetPrinterFailure` as it wasn't used any more and referenced a non-existing function (`set_printer()`).
* Moved the `README` text into `lib.rs` and generated `README.md` via `cargo readme` (with `README.tpl` template to have intra-doc links resolved correctly).
* Added `rustfmt.toml` to help with automatic line wrapping of comments via `cargo fmt`.
* Made the `ErrorHook` type public. It is referenced in the public docs and `set_hook()` (which is public) so I assumed this was intended.
=> Docs overhaul

src/handler.rs
Thanks for miette! We've been having a great time using it in
cargo-nextest to print out nicely-formatted errors.
I noticed a bug while testing out miette -- the `ansi_colors` method
does not set ANSI colors properly.
By the way, I do not believe miette should use RGB colors at all --
default colors in applications must be restricted to 12 ANSI colors. See
https://rust-cli-recommendations.sunshowers.io/colors.html#color-palettes
for why. I'm happy to disable RGB colors in all the applications I
maintain, but doing so globally is something for upstream to consider.
=> fix: set correct field in MietteHandlerOpts::ansi_colors

src/named_source.rs, src/protocol.rs
SourceSpan is just a pair of usizes, so it's cheap to copy.
=> feat: make SourceSpan implement Copy

src/eyreish/into_diagnostic.rs
This patch expands on the effects of using IntoDiagnostic and warns
users of potential loss of information when using it on `Diagnostic`
types.
This patch is related to #160.
=> Expand documentation on IntoDiagnostic

miette-derive/src/diagnostic.rs, miette-derive/src/diagnostic_source.rs, miette-derive/src/forward.rs, miette-derive/src/lib.rs, src/diagnostic_chain.rs, src/eyreish/into_diagnostic.rs, src/handlers/debug.rs, src/handlers/graphical.rs, src/handlers/narratable.rs, src/lib.rs, src/protocol.rs, tests/test_diagnostic_source_macro.rs
Hi!
Currently, miette does not support error causes which contain a `Diagnostic`. 
This draft tries to change that. It is related to #164 , as I worked with @TheNeikos on implementing this.
Tell me what you think! :heart:
---
Please note that I will rebase this PR until we all agree on a way forward!
=> Add caused_by to Diagnostic

miette-derive/src/diagnostic_source.rs, tests/test_diagnostic_source_macro.rs
Currently only a simple borrow is performed in some cases, and as_ref in other. AsRef is however not always implemented and `&Box<dyn Diagnostic>` does not implement `Diagnostic`. This patch makes use of `Borrow` that correctly handles both cases.
Problems before:
```
error[E0599]: the method `as_ref` exists for reference `&AnErr`, but its trait bounds were not satisfied
--> tests/test_diagnostic_source_macro.rs:14:17
|
5   | struct AnErr;
| ------------- doesn't satisfy `AnErr: AsRef<_>`
...
14  | #[derive(Debug, miette::Diagnostic, thiserror::Error)]
|                 ^^^^^^^^^^^^^^^^^^ method cannot be called on `&AnErr` due to unsatisfied trait bounds
|
= note: the following trait bounds were not satisfied:
`AnErr: AsRef<_>`
which is required by `&AnErr: AsRef<_>`
note: the following …
```
=> Allow using smartpointers with source_diagnostic

src/handlers/json.rs
See for instance how this json parser gets mad:
```json
{
"hello": "\\ \" \n \r \t \b \f"
"oops": "this is evil \' oh no!"
}
```
=> Don't escape single-quotes, that's not valid json

src/source_impls.rs
Adding the ?Sized bound allows use of Arc<str> as a source code type
=> Implement SourceCode for Arc<str> (and similar types)

.github/workflows/ci.yml, Cargo.toml
https://github.com/palfrey/miette/runs/7059873509?check_suite_focus=true demonstrates the bug.
This PR:
* Adds a build with the minimal supplied versions from the Cargo.toml (which needs nightly for the -Z flag) to check for the problem
* Upgrades supports-color to 1.1.1 which is the first version that compiles successfully
=> Doesn't compile with supports-color 1.0.4

src/handlers/graphical.rs, tests/graphical.rs
In some cases the source can be completely empty -- handle that in a reasonable fashion.
=> fix(graphical): handle an empty source

src/handler.rs, src/handlers/graphical.rs, src/handlers/narratable.rs, src/lib.rs
Related to #191 
The default behaviour remains to render the cause chain, but knobs are exposed to allow avoiding cause chain rendering.
=> Allow miette users to opt-out of the rendering of the cause chain

README.md, src/lib.rs
Cargo has built-in since [v1.62](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-162-2022-06-30), so we don't need `cargo-edit`.
=> docs: remove sentence about `cargo-edit`

.github/workflows/ci.yml, src/eyreish/context.rs, src/eyreish/error.rs, src/eyreish/fmt.rs, src/eyreish/mod.rs, src/eyreish/ptr.rs, src/handler.rs, src/source_impls.rs, tests/compiletest.rs
Fixes #189.
This PR essentially just ports the changes from anyhow ([initial PR](https://github.com/dtolnay/anyhow/pull/134), [cleanup commit](https://github.com/dtolnay/anyhow/commit/62673e2ccf8f0b20519c3a610f8d8b5aaf99e6f9), [follow-up PR](https://github.com/dtolnay/anyhow/pull/144), [follow-up PR](https://github.com/dtolnay/anyhow/pull/145)) in one go.
The general theme of the changes is to use raw pointers for as much of the vtable shenanigans as possible to avoid the assumptions that references carry.
=> Resolve Miri's concerns around unsafe code

src/handlers/graphical.rs, tests/graphical.rs
Fixes #87 and #97.
Turns out that reliably determining the width of a string when displayed in a terminal is impossible without using ANSI escapes to get the current cursor position. Relying on the ANSI escapes is an option, but won't work if your output isn't a TTY. Supporting non-TTY output is important for things like redirecting error messages to a file, so I implemented a _mostly correct_ label alignment process that makes some specific tradeoffs. In the future, we could also add the escape-based option, and just fall back to this behavior on non-TTY output.
Back in https://github.com/zkat/miette/issues/87#issuecomment-1137930566, I had an idea for a hack to fix tab alignment while still respecting the terminal's tabstop setting. Unfortunately, I couldn't figure out a way to make …
=> Fix graphical label alignment issues 

.github/workflows/ci.yml, Cargo.toml
The latest release of `once_cell` (1.15.0) [bumped their msrv to 1.56.0][1]. Miette didn't previously declare an MSRV, but we have a CI pass that tests against rust 1.54.0. As a result, CI is currently broken.
[1]: https://github.com/matklad/once_cell/blob/master/CHANGELOG.md#1150
There are a few options here:
- Bound our `once_cell` dependency as `<1.15.0`, and continue testing against rust 1.54.0.
- Bump the CI pass to rust 1.56.0, but don't declare a MSRV for `miette` itself
- Bump the CI pass and declare an MSRV (what I implemented in this PR)
I don't have strong opinions about which of these options to go for, it's really up to the `miette` maintainers. Happy to switch out this PR for one of the other options if you would prefer.
=> Declare minimum supported rust version at 1.56.0 (fixes CI)

src/eyreish/error.rs, src/eyreish/wrapper.rs, tests/test_boxed.rs
This patchset:
* Adds a `Report::new_boxed` method.
* Finishes up the forwarding `Diagnostic` impls for `BoxedError` and a couple of other structs.
* Implements `AsRef<dyn StdError>` for `Report` since it's useful for some purposes, including the tests in the next commit.
* Adds tests for all of the above.
Closes #212.
=> Add Report::new_boxed + more fixups + tests

src/source_impls.rs
SourceCode is implemented for &str, String, and &[u8] but it is missing an impl for `Vec<u8>`.
=> Implement `SourceCode` for `Vec<u8>`

miette-derive/src/code.rs, miette-derive/src/forward.rs, miette-derive/src/help.rs, miette-derive/src/url.rs, tests/derive.rs
Closes #211.
The bug was caused by user structs and enums using the same lifetime (`'a`) that was used by some of the derived functions (`help`, `url`, `code`) in their signatures. So for the following example:
```rust
use miette::Diagnostic;
use thiserror::Error;
#[derive(Debug, Diagnostic, Error)]
#[error("foo")]
#[diagnostic(help("foo"))]
pub enum Foo<'a> {
Bar { bar: &'a str },
}
```
you would get derived code that looks like this:
```rust
use miette::Diagnostic;
use thiserror::Error;
#[error("foo")]
#[diagnostic(help("foo"))]
pub enum Foo<'a> {
Bar { bar: &'a str },
}
impl<'a> miette::Diagnostic for Foo<'a> {
fn help<'a>(
&'a self,
) -> std::option::Option<std::boxed::Box<dyn std::fmt::Display + 'a>> {
#[allow(unused_variables, deprecated)]
match self {
Self::Bar { bar } => { …
```
=> Elide lifetimes in derived functions

src/handlers/graphical.rs, tests/graphical.rs
This also changes the behavior with spans including a CRLF line-ending. Before the panic bug was introduced, these were rendered with the CRLF being two visual columns wide. Now, any span extending past the EOL is treated as including one extra visual column. See https://github.com/zkat/miette/issues/215#issuecomment-1301560478 for an example of this.
This PR notably does not fix the rendering bug with spans including the EOF. These were rendered incorrectly before the panic bug was introduced. @Boshen mentioned that they were seeing a panic with EOF in #215, but I haven't been able to reproduce that. We may want to wait for a response from them before merging this, since it seems like I'm missing something here.
=> fix(graphical): Fix panic with span extending past end of line (#215)

README.md, src/lib.rs
Being able to construct ad-hoc errors is an important part of writing applications so I feel `miette::miette!` deserves to take up some space under this heading
=> Mention miette::miette! macro under "... in application code"

src/handlers/graphical.rs, src/handlers/narratable.rs, src/protocol.rs, tests/graphical.rs
Currently, the severity of the parent error is shown as the severity of related errors.
This PR fix it.
Closes #232
=> Fix wrong severity of related errors

Cargo.toml, src/handler.rs, src/handlers/theme.rs
Draft for now, switching out `atty` for `is-terminal` per #228
=> Switch out `atty` for `is-terminal`

.github/workflows/ci.yml, CONTRIBUTING.md, Cargo.toml, README.md, README.tpl, src/dynamic_diagnostic.rs, src/eyreish/macros.rs, src/lib.rs, src/miette_diagnostic.rs, src/protocol.rs, tests/test_chain.rs, tests/test_downcast.rs
Draft for dynamic diagnostics for design discussion. 
Implements #259
=> Add dynamic diagnostic

Cargo.toml, src/eyreish/macros.rs, src/miette_diagnostic.rs, src/protocol.rs
Need to add serde to `MietteDiagnostic` too, when #262 is merged
=> Add `serde` support

src/eyreish/ptr.rs, src/handlers/debug.rs, src/handlers/json.rs, src/handlers/narratable.rs, src/protocol.rs
This is primarily aimed at making `SourceSpan` and `SourceOffset` usable in const contexts.
Constifiable functions were found with the `clippy::missing_const_for_fn` lint, though it reported at least two false positives.
Fixes #261
=> feat: Constify many functions

src/handlers/graphical.rs, tests/graphical.rs, tests/test_diagnostic_source_macro.rs
Previously `#[diagnostic_source]` did not correctly render the inner diagnostic. This PR fixes that.
There's a change here that can be considered controversial:
- Only print newlines when there is an actual header (in ad9d0378ddd6dd4a6b9e650dd6aa62116da65910)
I am fine with removing it, but then the nested diagnostic source will be offset by one line and appear floating when it does not print a header.
PS: This PR also includes things from #169. I will rebase once that is merged (hopefully?)
=> Render inner diagnostics

README.md, README.tpl
the links point to structs, whereas it should be traits
=> docs: fix broken links

README.md
- Duplicated `miette` import seems not to have any educational purpose, so I combined everything into a single import.
- `len` computation seems to be unused.
=> docs: a little cleaning in README

src/protocol.rs, tests/test_derive_source_chain.rs
Adds `std::error::Error` impls for `Box<dyn Diagnostic + Send + Sync>` (and other variants).
Fixes #272.
=> fix(protocol): add StdError impl for Box<dyn Diagnostic + Send + Sync>

miette-derive/src/label.rs, miette-derive/src/lib.rs, src/handlers/graphical.rs, src/miette_diagnostic.rs, src/protocol.rs, tests/graphical.rs, tests/test_diagnostic_source_macro.rs
As discussed in #91 and #208, it is sometimes desirable for the line/column numbers in a diagnostic to reference a label as opposed to the start of the context. However, there has to be a way of identifying which label to reference.
This PR implements one possible mechanism: a `label(primary)` attribute which acts just like `label`, except it marks a single label as being "primary". For example, this program:
```rust
use miette::{Diagnostic, SourceSpan};
use thiserror::Error;
#[derive(Error, Debug, Diagnostic)]
#[error("Primary span error")]
struct PrimarySpanError {
#[source_code]
src: String,
#[label(primary)] // note the new attribute parameter
span: SourceSpan,
}
fn main() -> miette::Result<()> {
Err(PrimarySpanError {
src: String::from("Hello\nworld"),
span: (7..10).into(),
} …
```
=> Add support for primary label in specifying line/col information

tests/test_diagnostic_source_macro.rs
A couple of tests require `fancy-no-backtrace`, so mark them accordingly.
=> tests: Fix `cargo test` with default features.

miette-derive/src/source_code.rs, tests/derive.rs
=> Allow optional sources in derive

README.md
An example in README.md makes use of `miette::NamedResult` . It is imported in the second "example-step", but already used in the first one. Beginners, that copy the example step-by-step to understand it, will run into compile errors, as `NamedResult` was not imported.
=> docs(README): Move import of `NamedResult` to where it is used

src/handlers/graphical.rs, tests/graphical.rs
This fixes a panic when an error starts inside a Unicode code point. The range is extended to start (or end) at the beginning (or end) of the character inside which the byte offset is located.
Fixes zkat/miette#223. Unit tests provided in that issue by @Benjamin-L (lightly modified).
=> Extend error text span to whole code points

src/handlers/graphical.rs, tests/graphical.rs
This bug was originally identified in https://github.com/zkat/miette/pull/312#issuecomment-1791075099.
The bad output looked like this:
```
╭─[bad_file.rs:2:4]
1 │ source
2 │   👼🏼text
·   ─▲
·    ╰── this bit here
3 │     here
╰────
```
Another possible option for the output (other than the one I implemented) would be
```
╭─[bad_file.rs:2:4]
1 │ source
2 │   👼🏼text
·    ▲
·    ╰── this bit here
3 │     here
╰────
```
I prefer pointing the `▲` at the first column of the wide char rather than the second, but can see an argument that pointing at the second column is visually communicates that the span is unaligned. I think that's pretty niche, and would be surprised if any users are generating unaligned spans on purpose.
---
I also included a minor refactor in the PR, removing an unnecessary …
=> Fix formatting bug when an empty span is not aligned to a char boundary

Cargo.toml, src/error.rs, src/lib.rs
=> Make `miette-derive` be able to be turned off

src/handler.rs, src/handlers/graphical.rs, src/lib.rs, tests/graphical.rs
Hi!
Thanks for the project, it's really nice.
I'm running into problems when my report has a URL in it — it's wrapping to the next line on `/` boundaries. This is both a cosmetic problem and a functional one as the link cannot be clicked.
```rust
fn main() {
let url = "https://files.pythonhosted.org/packages/bd/24/11c3ea5a7e866bf2d97f0501d0b4b1c9bbeade102bb4b588f0d2919a5212/Werkzeug-2.0.1-py3-none-any.whl";
let report = miette::Report::msg(format!("There was a failure with {url}")).context("Oh no");
eprint!("{report:?}");
}
```
```
× Oh no
╰─▶ There was a failure with https://files.pythonhosted.org/packages/
bd/24/11c3ea5a7e866bf2d97f0501d0b4b1c9bbeade102bb4b588f0d2919a5212/Werkzeug-2.0.1-py3-none-any.whl
```
After some digging, I discovered this behavior is due to defaults in `textwrap` …
=> Expose additional `textwrap` options

README.md, src/lib.rs
Closing #96 
This is just a tiny docs change I that @esoterra proposed in an old issue. I thought it was still relevant, so I added an example for it. Let me know if this is how you like it or not :)
=> add example to README and docs

src/handlers/graphical.rs, tests/graphical.rs
See #317. This contributes a test for #317  and then fixes the bug :)
Closes #317 
The bad screenshot from #317 
now becomes this with the proposed changes:
Note that there were actually two subtle bugs. One was the double arrow in the gutter problem, which also occurred when rendering without ansi escape codes. However, this line
https://github.com/zkat/miette/blob/a8b4ae012aa0cf03b53a18f013c2b3f76c5040e7/src/handlers/graphical.rs#L611
Also did not work when the gutter contains ansi escape codes. It extends to the `width` variable, but when the string contains ansi codes it does not actually add any spaces since it thinks the escape codes have width as well. They of course do not, so the output doesn't look right. Unfortunately this is quite hard to make tests for.
=> rendering bug on small spans in large spans

src/handler.rs, src/handlers/graphical.rs, tests/graphical.rs
Hi!
I want to be able to disable line wrapping entirely for logging runs and for users that would rather rely on their terminal's line wrapping. This pull request introduces a `wrap_lines` option which disables wrapping. Since `textwrap::fill` is used insert prefixes as well, this requires a little implementation to preserve that behavior.
=> Add `wrap_lines: bool` option allowing wrapping be disabled entirely

src/handlers/graphical.rs, tests/graphical.rs
Hey, here are some local changes I made that might be useful.
In the first commit I tried to make the `render_snippets` function more readable and fixed what I think was a bug.
(Looks like it would not merge more than two contexts if the last context didn't overlap the first)
In the second commit I restricted finding the primary label to those in the current context.
This makes it so that the header above each snippet points to code in the snippet.
(It is especially useful for `SourceCode` implementations that wrap multiple files)
Example showing different headers for different snippets:
=> Clean up render snippets

tests/color_format.rs
Previously, these tests would have spurious failures when `NO_COLOR` or `FORCE_COLOR` was set in the user's environment, since we weren't clearing one variable before testing a value for the other one. The previous version of the code also did not restore environment variable values on panic, which could cause spurious failures in other tests after one test fails.
=> Improve robustness of color_format tests

src/handlers/graphical.rs, tests/test_diagnostic_source_macro.rs
Hi @zkat!
The default `GraphicalReportHandler` disables the printing of cause chains for any inner errors (errors `related()` to a source diagnostic) when it disables nested footer printing. This results in lost cause chain information when printing with the default report handler.
Before this PR:
After this PR:
This PR simply re-enables that cause-chain printing by removing the line where it was disabled. It looks like that line was added as part of the initial feature implementation in #170, but the current behavior of not printing the cause chains of inner errors (I found) surprising and it led me to scour my codebase trying to find where the source error was being lost.
If, however, retaining the current default behavior is preferred, I can implement a couple of methods on …
=> fix(graphical): render cause chains for inner errors

src/handler.rs
`GraphicalReportHandler::new()` calls `GraphicalTheme::default()`
https://github.com/zkat/miette/blob/7ff4f874d693a665af4df40f4e94505013e3e262/src/handlers/graphical.rs#L52
which calls `std::io::stdout().is_terminal()` and `std::io::stderr().is_terminal()`
https://github.com/zkat/miette/blob/7ff4f874d693a665af4df40f4e94505013e3e262/src/handlers/theme.rs#L72
but this default theme is overridden by `with_theme(theme)`.
=> fix(handler): remove the two extra `is_terminal` sys call from `MietteHandlerOpts::build`

src/eyreish/wrapper.rs
=> Don't override provided source code

README.md, src/lib.rs, src/named_source.rs, tests/graphical.rs, tests/narrated.rs, tests/test_derive_attr.rs, tests/test_json.rs
Fixes: #236 
This is a simple direct implementation that just makes NamedSource generic over a SourceCode type parameter. It would be nice if we could give the type parameter a sensible default so that existing diagnostics don't break. I'll test various approaches to make this more backwards compatible over the next few days. 
Maybe keeping the source in a `Box`, allowing `S` to be `?Sized`, and then defaulting `S` to `dyn SourceCode + 'static` but I'm not sure how to change the type of `NamedSource::new` to allow for that, since function arguments must be `Sized`.
=> Allow inner source type of a NamedSource to be borrowed directly

.github/workflows/ci.yml, Cargo.toml, src/handler.rs, src/handlers/graphical.rs, src/highlighters/blank.rs, src/highlighters/mod.rs, src/highlighters/syntect.rs, src/lib.rs, src/named_source.rs, src/protocol.rs, tests/graphical.rs
To do after finalizing design:
* test cases
* better docs
=> add syntax highlighting support with syntect crate

src/handlers/graphical.rs, tests/graphical.rs
This option allows to globally change the default `(link)` display text with any other text provider by users.
I investigated if it was possible to change the display text per error, but I was not sold of any option I tried. I think this is a pretty simple addition that can help people like me that just want to change this text for all the errors.
Fixes #331
=> feat(fancy): Add option to change the link display texts

.github/workflows/ci.yml, Cargo.toml, miette-derive/Cargo.toml, tests/graphical.rs
The commit e5c7ae4 seemed to (potentially erronously?) remove a number of spaces following the left `|` bar of some graphical report handler tests. That change had no effect on the `syntax_highlighter_on_real_file()` test, presumably because the trailing whitespace is removed by `strip_ansi_escapes::strip_str()`, but it did break the `triple_adjacent_highlight()` and `non_adjacent_hightlight()` tests. Restoring the spaces removed in e5c7ae4 fixes the failing tests on main.
=> fix(tests): revert test-breaking changes of e5c7ae4

src/protocol.rs, tests/test_diagnostic_source_macro.rs
Hello again! Nice and small change this time :)
The `#[diagnostic_source]` attribute already worked for `Box<dyn Diagnostic>`, but not for the highly-related `Box<dyn Diagnostic + Send>` and `Box<dyn Diagnostic + Send + Sync>` types!
It looks like someone already solved this issue for `std::error:Error` with a `macro_rules!` implementation, so I've done the same here to let those new cases compile! Without those `Borrow<dyn Diagnostic>` impls, you end up with compiler errors coming from inside of the derive macro:
Let me know if you have any questions! I'll separately try to sort out those failing tests (unrelated to this change) in another PR :)
=> feat(derive): enable more boxed types to be #[diagnostic_source]

src/named_source.rs, src/protocol.rs
One-liner sanding off a small rough edge I came across: using `NamedSource<String>` (instead of simply `String`) severely limits which traits can be derived for the wrapping diagnostic. In my case, I lost the ability to clone my error!
I've brought things in line with https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits, leaving out `Copy`, `Display`, and `Default`, since those derives are either not possible or don't feel useful. The ones I've added here make sure people can `.clone()` errors, compare them, sort them, and use them in `HashSet`s / `HashMap`s.
I also added `Ord` derives to the `SourceSpan` and `SourceOffset` types for the same reason!
=> feat(source): derive common traits for NamedSource, SourceSpan, and SourceOffset

miette-derive/src/label.rs, src/lib.rs
The most important one is adding the documentation to lib.rs. I didn't know the documentation was there and the README.md was built out of it.
The rest is removing pointless or redundant code.
(The change about chaining the iterators started from a compilation warning about an unnecessarily mutable variable. However
I'm not sure how I was getting that warning, I cannot reproduce it anymore. But I think the change it still worthwhile anyway, but
opinions may vary :))
=> Label collection fixes and cleanup

src/handlers/graphical.rs, tests/graphical.rs
Fixes: https://github.com/zkat/miette/issues/219
When a snippet couldn't be read (typically because the span didn't fit within the source code), it and the rest of the diagnostic were silently dropped, which was confusing to the developer.
Now, in place of the snippet, print an error message with the name of the failed label and the error it triggered, then proceed with the rest of the diagnostic (footer, related, ...)
This is what it looks like:
=> fix(invalid span): skip the snippet when read_span fails

.github/workflows/ci.yml, Cargo.toml, src/eyreish/mod.rs, src/handler.rs, src/handlers/mod.rs, src/lib.rs
* closes https://github.com/zkat/miette/issues/346
* closes https://github.com/zkat/miette/pull/326
I added 
* `fancy-base` feature to enable exports for the `fancy` feature
* `fancy-no-syscall` feature to disable all syscalls
* a `wasm` ci check to ensure future changes.
`target_family = "wasm"` will not work in this case because `terminal_size` will not compile under `wasm32-unknown-unknown`, the dependency has to be excluded.
=> feat: add feature "fancy-no-syscall" for wasm targets

README.md
I only found out how to use this after reading all the test cases.
I think it's better to appear in the readme. hah~
=> doc: add `severity` example

.github/workflows/ci.yml
Add a CI to ensure that both README.md and lib.rs get update at the same time and avoid issues such as #343 and #351
=> ci(doc consistency): check that lib.rs and README.md are consistent

src/eyreish/wrapper.rs, src/handlers/graphical.rs, tests/derive.rs, tests/graphical.rs, tests/test_diagnostic_source_macro.rs
Fixes #333
Here is an error now nicely wrapping (with the 2 char padding on either side) of a 50-char wide terminal:
=> fix(graphical): fix nested error wrapping

README.md, src/lib.rs
One example:
```sh
dape-tester on  main [!+?] is 📦 v0.1.0 via 🦀 v1.79.0-nightly via ❄️  impure (nix-shell-env)
❯ cargo clippy --all-targets
warning: unused imports: `IntoDiagnostic`, `WrapErr`
--> src/my_internal_file3.rs:1:22
|
1 | use miette::{miette, IntoDiagnostic, Result, WrapErr};
|                      ^^^^^^^^^^^^^^          ^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: question mark operator is useless here
--> src/my_internal_file3.rs:6:5
|
6 | /     Ok(version
7 | |         .parse()
8 | |         .map_err(|_| miette!("Invalid version {}", version))?)
| |______________________________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark
= note: …
```
=> Fix clippy lints in docs

README.md, src/lib.rs
The white line breaks in the `alt` attribute prevented the `single-line-example.png` image from being displayed.
=> fix(docs): `alt` attribut for `single-line-example.png`

src/handlers/theme.rs
=> fix: setting NO_COLOR should not print ansi codes for non-terminals

src/handlers/graphical.rs, src/handlers/narratable.rs
This improves `get_lines()` logic by using a string-buffer with a capacity hint. That avoids growing the buffer from zero each time, saving a bunch of reallocations.
This is a forwarded patch from https://github.com/oxc-project/oxc/pull/3897, see there for further explanations and datapoints.
=> perf(handlers): optimize string-buffer reallocations

src/protocol.rs
This can be used to avoid awkward `start..(end + 1)` constructions, which will trigger the `clippy::range_plus_one` lint.
I added a single impl for `InclusiveRange` rather than a blanket `impl<T: RangeBounds> From<T> for SourceSpan` for two reasons. The first is that the blanket impl would be a breaking change (because dependent crates may currently define a type `T: RangeBounds` and also have `impl From<T> for SourceSpan`). The second is that this would allow one-sided ranges (`..x`, `x..`). In order to support bounded-below ranges, we would need to change `SourceSpan` so that `length` may depend on the the specific `SourceCode` instance. That seems like an unlikely use case.
=> feat(SourceSpan): add impl From<InclusiveRange>

Cargo.toml, src/handlers/graphical.rs
The goal of this PR is a tiny bit of dependency pruning by not enabling the default "smawk" feature.
While this changes the default line wrapping behaviour slightly, I hope that is okay, but users can also re-enable optimal fit by adding textwrap to their Cargo.toml
=> Disable textwrap::smawk feature

src/eyreish/error.rs, tests/test_boxed.rs
Fixes #369
The culprit was:
https://github.com/zkat/miette/blob/ea4296dacec3b0e4762281d9d115c1bd69ecfac3/src/eyreish/error.rs#L728
In conjunction with:
https://github.com/zkat/miette/blob/ea4296dacec3b0e4762281d9d115c1bd69ecfac3/src/eyreish/error.rs#L531-L537
Which converts a `Box<ErrorImpl<E>>` into the `Box<dyn Diagnostic>`, hence the resultant object ends up with the empty `Diagnostic` impl defined above!
This fix moves the `_object` out of the `Box<ErrorImpl<E>>` to create a `Box<E>` before conversion to `Box<dyn Diagnostic>`, attaching the correct `Diagnostic` impl for the *original* error `E`.
Miri seems happy, and I've actually only added safe code, even though it's in an `unsafe` function because of `.boxed()` which I left untouched.
---
As a side note, the only reason converting …
=> Fix #369 (Loss of `Diagnostic` information when `Report` is converted to `Box<dyn Diagnostic>`)

src/handlers/graphical.rs
With the existing formatting, VSCode doesn't like to group the line and column with the link. You can check this with:
```sh
echo -e '-[\e[1m./README.md\e[0m:1:2]'
```
This is arguably a VSCode bug, but I think it makes sense to format the entire `name:line:col`, both logically and to ensure maximum compatibility with various terminal emulators.
=> fix(graphical): format entire link instead of just name

src/handlers/graphical.rs, tests/graphical.rs
=> Handle invalid UTF-8 in source code

src/eyreish/error.rs, src/eyreish/into_diagnostic.rs
There's no nice way to construct a bare `Report` from a regular `Error` type. You can construct `Result<_, Report>` from `Result::<_, E: ...>`, but not from an error by itself.
My workaround where `e: impl Error + Send + Sync + 'static` is to do `Err::<(), _>(e).into_diagnostic().unwrap_err()`, which obviously is ugly.
I added a `Report::from_err()` method that solves this problem in the same way as the `IntoDiagnostic` trait, by using its `DiagnosticError` type.
=> feat: add `from_err()` method to `Report`

Cargo.toml
This prevents creating implicit features for them which can be confusing (and duplicates features).
=> Use `dep:` syntax for dependencies in features.

src/diagnostic_impls.rs, src/lib.rs
I've been working with some code that looks like this:
```rust
trait DiagnosticTryFrom<Input>: Sized {
type Error: Diagnostic;
fn try_from_diagnostic(input: Input) -> Result<Self, Self::Error>;
}
```
And so logically it makes sense to create a blanket implementation on top of `TryInto`:
```rust
impl <I, O> DiagnosticTryFrom<I> for O where O: TryFrom<I>, O::Error: Diagnostic {
type Error = O::Error;
fn try_from_diagnostic(input: I) -> Result<Self, Self::Error> {
O::try_from(input)
}
}
```
Which works very well for my own `TryFrom` implementations -- but not so well when there's a `From` implementation available. Every `From` implementation [gets a blanket implementation of `TryFrom` with an error type of `Infallible`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html#generic-implemen …
=> Implement `Diagnostic` for `Infallible`

src/highlighters/mod.rs
This happens when building with `--features fancy`.
=> fix(clippy): Fix `needless_return` lint.

src/lib.rs
Move use NamedSource a bit up, since now it looks like it is not imported.
=> Small refactor of doc tests

src/handlers/graphical.rs, tests/test_diagnostic_source_macro.rs
At the moment outer source code is supplied to inner related errors but not to causes. This PR changes that.
This allows late-supplied source code to be supplied using concrete types. Comparisons below…
Firstly, if we wrap our inner error with some well-typed outer wrapper:
```rust
#[derive(thiserror::Error, Debug, miette::Diagnostic)]
#[error("inner-error")]
struct InnerError {
#[label("inner-label")]
label: (usize, usize),
}
#[derive(thiserror::Error, Debug, miette::Diagnostic)]
#[error("outer-error")]
struct OuterError {
#[source_code]
source_code: String,
#[diagnostic_source]
inner: InnerError,
}
fn main() -> miette::Result<(), miette::Report> {
Err(OuterError {
source_code: "source code".to_string(),
inner: InnerError { label: (7, 4) },
})?
}
```
At the moment we don’t get any source …
=> Inherit source code to causes as well as related errors

src/eyreish/context.rs, src/eyreish/wrapper.rs
Implement `WrapError` for `Option<T>`. This is inline with `anyhow` that also implements `Context` for `Option<T>`.
The implementation requires us to introduce a `DisplayError` internal only type, that creates an error from a type that only implements `Display` (`Report::from_adhoc` requires the type to also implement `Debug`, but `WrapError` only requires it to implement `Display`).
For this I copied `MessageError` and adapted it to implement `Debug` using the underlying type's `Display` impl. This is a bit of a hack, but anyhow does [something similar][1].
Closes #408
[1]: https://docs.rs/anyhow/latest/src/anyhow/wrapper.rs.html#34
=> feat: Implement `WrapError` for `Option`

src/handler.rs, src/handlers/graphical.rs, tests/test_diagnostic_source_macro.rs
This PR adds a new option to the `MietteHandlerOpts` that allows rendering related errors as nested, like this:
implements #416
=> Add show_related_errors_as_nested-option

src/handlers/graphical.rs, tests/graphical.rs, tests/test_diagnostic_source_macro.rs
#358 introduced a new behavior: if a diagnostic has no `code`, the rendered report will contain a leading newline.
I'm not sure if this was an intentional change or an unintended side effect, but as a long-time miette user, I wouldn't expect my rendered report to include an extra leading newline - whether I'm outputting to the terminal, displaying in web page, or running snapshot tests. So I opened this PR.
Please let me know if I've misunderstood anything.
=> fix(graphical): prevent leading newline when no link/code

src/handlers/graphical.rs, tests/graphical.rs
=> feature: add support for disabling the primary label line/col information

.github/workflows/ci.yml, src/handler.rs
This PR increases the `highlighter` config priority over the `rgb_colors` config. It resolves https://github.com/zkat/miette/issues/337.
Currently, enabling the `syntect-highlighter` feature is not enough to actually enable syntax highlighting, because the default `rgb_colors` config disallows it (more info and current workarounds in https://github.com/zkat/miette/issues/337). It would be desirable if users could use syntax highlighting simply by adding the `syntect-highlighter` feature.
Also, the current behavior is not consistent. For instance, when a custom highlighter is set (instead of syntect's), `rgb_colors` is already disregarded. When a custom highlighter is set and `syntect-highlighter` is disabled, even the `color` config is disregarded (it shouldn't be).
I kept 2 commits that …
=> fix(highlight): increase syntax highlighter config priority

Cargo.toml, miette-derive/Cargo.toml, src/panic.rs
Hello,
I'm using `watchexec`, which depends on `miette` and `thiserror 2.x`. `miette` currently depends on `thiserror 1.x`, which results in both versions being included in the dependency tree.
I ran `cargo test`, but I'm not sure if there's anything else I should check. Please let me know if there's anything else I need to do.
Thanks!
=> update `thiserror` from 1.0.56 to 2.0.11

Cargo.toml, src/error.rs, src/eyreish/error.rs, src/eyreish/into_diagnostic.rs, src/handler.rs, src/highlighters/syntect.rs, src/lib.rs, src/panic.rs, src/protocol.rs
Closes #435 and should just be a patch-level SemVer change!
Currently blocking the removal of `syn` from `kdl-rs`s dependency tree, but with this PR merged, that should become rather straightforward!
I also found and fixed a bug leading to compilation errors in `ffe374c`, some clippy lints, and reused some code in `53c8330`.
I also added tests wherever I was replacing `Error` or `Diagnostic` derives with something hand-written, just to be sure I wasn't changing any behavior!
=> Remove `thiserror` from dependencies

Cargo.toml, tests/color_format.rs
This is available since Rust 1.63, so no change in MSRV necessary.
=> chore: Use const init for Mutex
